### PR TITLE
Added correct returns for smaller matrices used with bigger workspaces

### LINKED ISSUE #22: Resize workspace to smaller system
Hello,
It seems that at the moment, for the eigen workspaces, a resize is only triggered if the size of the workspace is too small, but not if it is too large:
https://github.com/DynareJulia/FastLapackInterface.jl/blob/e0d766127dec795188402e2d7e75926f73039538/src/eigen.jl#L379

The function therefore returns invalid (too large) arrays for eigenvector and for eigenvalues.

### PR DESCRIPTION
**Pull request by louisponet**
This fixes #22

### CODE REVIEW

**Comment by jebej** [comment]
Wouldn't this make the output type-unstable?

**Comment by louisponet** [comment]
Hmm you are right. I'm actually not sure what's best to do, a `view` or a potential allocation... Always a view?

**Comment by jebej** [comment]
I suggested an alternate change in #25

**Comment by louisponet** [comment]
Could you try running a small benchmark comparing the type instability (If it's seen as a small union I think julia is very optimized nowadays for that stuff) vs always view vs your solution?

**Comment by jebej** [comment]
We won't see an impact in the factorization itself, but it would affect any code using the arrays after the factorization. Given how the behavior was already to do a full resize when the workspace was too small, it seems appropriate to also do it when it's too big.

This is really just a convenience when you want to keep using the same workspace (for whatever reason). People who care about performance would either resize manually, or use different workspaces for different array sizes.

**Comment by louisponet** [comment]
That is a fair statement. Still, I think it should be possible to allocate a `ws` of the largest size of your matrix and use it for all random sizes that are smaller than that without resizing continuously. So I'd like to see how much it actually matters. Let me run some tests and come back to you later. Thank you though for noticing.

**Comment by jebej** [comment]
Note that currently the tests you added are not testing that the correct eigenvectors are returned. The vectors are returned "stacked" in the array as if it was a vector. As is, I believe that if you take the `view` of an eigenvector matrix, it will select the wrong entries. You would need to `vec` first.

**Comment by louisponet** [comment]
So I've done some quick benchmarking. Using always views versus always matrices does not impact speed at all, so from the type stability point of view just returning always a view seems to be the way to go. 
I say this because from the allocations and speed point of view, I find that always resizing in my test case led to 45 allocations and slower versus only resizing when needed + views with 16 allocations and faster. 

If it seems like a good compromise to you to return always a view, I'd like to stick with that. 

Hmm I see, I'm not sure about that last point you made, let me investigate that. If it's the case I think a reshape on a `view(ws.Z, 1:ldz^2)` or similar should do the trick no? I'll add some tests for that though.

**Comment by louisponet** [comment]
Come to think about it, another possibility is to simply resize the ws.w and ws.Z since this sizes are known and not resize ws.work. I think that might be the best solution actually

**Comment by jebej** [comment]
This is what I meant regarding the view:

```julia
julia> H1 = rand(Float64,5,5); H1 = Hermitian(H1+H1');

julia> ws = HermitianEigenWs(rand(6,6), vecs=true);

julia> w1, Z1 = eigen(H1);

julia> w,Z = LAPACK.syevr!(ws,'V','A',H1.uplo,copy(H1.data),0.0,0.0,0,0,-1.0,resize=true);;

julia> Z1
5×5 Matrix{Float64}:
 -0.403107   0.557398   0.15559    -0.542529  -0.456362
 -0.638345  -0.54668   -0.0562142   0.282581  -0.45896
  0.32796   -0.267081  -0.716273   -0.448774  -0.326595
  0.52544   -0.272605   0.615025   -0.058724  -0.517586
  0.215351   0.494775  -0.285182    0.648817  -0.454455

julia> view(Z,1:5,1:5)
5×5 view(::Matrix{Float64}, 1:5, 1:5) with eltype Float64:
 -0.403107  -0.54668   -0.716273  -0.058724  -0.454455
 -0.638345  -0.267081   0.615025   0.648817   0.0
  0.32796   -0.272605  -0.285182  -0.456362   0.0
  0.52544    0.494775  -0.542529  -0.45896    0.0
  0.215351   0.15559    0.282581  -0.326595   0.0

julia> Z
6×6 Matrix{Float64}:
 -0.403107  -0.54668    -0.716273  -0.058724  -0.454455  0.0
 -0.638345  -0.267081    0.615025   0.648817   0.0       0.0
  0.32796   -0.272605   -0.285182  -0.456362   0.0       0.0
  0.52544    0.494775   -0.542529  -0.45896    0.0       0.0
  0.215351   0.15559     0.282581  -0.326595   0.0       0.0
  0.557398  -0.0562142  -0.448774  -0.517586   0.0       1.22726e-315
```

**Comment by jebej** [comment]
Note that I am against returning views, even if the above issue is fixed. That would go against the existing convention of returning arrays, and could lead to problems with downstream code.

**Comment by jebej** [comment]
Yes, I think you would need a reshape of a linear view, but that seems like opening the door to performance problems with two wrapper types like this: https://github.com/JuliaLang/julia/issues?q=is%3Aissue+is%3Aopen+reshape

**Comment by louisponet** [comment]
Ok, I must say I never liked views myself so I am in favor of a solution with only arrays. Sadly it's actually not possible to resize an array, and I can't really figure out a way to do it by hand by changing the `jl_array_t`. Maybe at this point we accept the one additional allocation of a new `Z` while resizing the `w` and keeping the larger `ws.work`. I will implement that and add a test checking the results.

**Comment by MichelJuillard** [comment]
> Come to think about it, another possibility is to simply resize the ws.w and ws.Z since this sizes are known and not resize ws.work. I think that might be the best solution actually

I also think that is the best solution. There is no cost at using too large a workspace in a Lapack function. I don't think it is possible to avoid the cost involved with resizing. The package is primarily provided for solving repeated problems of the same size. People who want to use it to solve successively different size problems should either bunch together problems of the same size or use different workspaces for different size problems. In the doc, we should discourage people to use blindly the resize feature for a large number of resizings (for example in a large loop with random occurrences of different size problems)

**Comment by louisponet** [comment]
To be honest, these sort of problems and ambiguities was why initially I thought automatic resizing was a bad idea. Anyway, if it's a feature we want to stick with, I think the proposed solution is ok.

**Comment by jebej** [comment]
The current solution in this PR adds a lot of code and logic, making the functions harder to read. The allocation reduction improvement from changing only the vector matrix, rather than resizing the whole workspace, doesn't seem worth it given people shouldn't be constantly changing size of their array, as @MichelJuillard mentions.

The solution I proposed in #25 is much simpler and seems preferable to me.

**Review by MichelJuillard — APPROVED** [review]

**Pull request merged**
