### PR TITLE
set CI for documentation

### PR DESCRIPTION
**Pull request by RohitRathore1**

### CODE REVIEW

**Comment by louisponet** [comment]
Hi Rohit,

As part of the redesign and the other PR I've already set up CI for documenter etc. Not sure if that's enough or not?

Cheers

**Comment by RohitRathore1** [comment]
> Hi Rohit,
> 
> As part of the redesign and the other PR I've already set up CI for documenter etc. Not sure if that's enough or not?
> 
> Cheers

Hi @louisponet , I had seen but that was not enough. Now using this template we can move forward without any problems. 

Thank you!

**Comment by louisponet** [comment]
Ok, what was missing?

**Comment by louisponet** [comment]
BTW my doctests won't work on julia 1.2

**Pull request closed without merging**
